FROM debian:buster-slim

RUN echo "deb http://archive.debian.org/debian/ buster main contrib non-free" > /etc/apt/sources.list && \
    echo "deb http://archive.debian.org/debian-security/ buster/updates main contrib non-free" >> /etc/apt/sources.list && \
    echo 'Acquire::Check-Valid-Until "false";' > /etc/apt/apt.conf.d/99no-check-valid-until

RUN apt-get update && \
  DEBIAN_FRONTEND=noninteractive apt-get -y install --no-install-recommends apt-utils bmake build-essential bzip2 ca-certificates \
  wget curl devscripts dh-make fakeroot git libcap-dev libelf-dev libseccomp-dev lintian lsb-release m4 pkg-config xz-utils && \
  rm -rf /var/lib/apt/lists/*

ENV OS_ARCH="arm64"
ENV GOLANG_VERSION="1.25.6"
ENV BUILD_DIR=/tmp
ENV GOPATH=$BUILD_DIR/go
ENV PATH=/opt/go/bin:$PATH
ENV GPG_TTY=/dev/console
ENV PACKAGE_DIR=$BUILD_DIR/package

COPY daemon.json /opt/daemon.json

RUN wget -qO- https://go.dev/dl/go${GOLANG_VERSION}.linux-${OS_ARCH}.tar.gz | tar -C /opt -xz
RUN chmod -R 777 /opt

CMD bash -c "cd $BUILD_DIR && \
  git clone --depth 1 --branch v${LIBNVIDIA_VERSION} https://github.com/NVIDIA/libnvidia-container.git && \
  cd $BUILD_DIR/libnvidia-container && \
  git checkout v${LIBNVIDIA_VERSION} && \
  DESTDIR=$PACKAGE_DIR make LIB_VERSION=${LIBNVIDIA_VERSION} LIB_TAG=${LIBNVIDIA_VERSION} install prefix=/usr GO111MODULE=auto && \
  mkdir -p $PACKAGE_DIR/etc/docker $PACKAGE_DIR/usr/lib/aarch64-linux-gnu $PACKAGE_DIR/DEBIAN && \
  mv $PACKAGE_DIR/usr/lib/* $PACKAGE_DIR/usr/lib/aarch64-linux-gnu/ 2>/dev/null || true && \
  cp /opt/daemon.json $PACKAGE_DIR/etc/docker/daemon.json && \
  cd $BUILD_DIR && \
  echo \"Package: libnvidia-container\" > $PACKAGE_DIR/DEBIAN/control && \
  echo \"Version: $LIBNVIDIA_VERSION\" >> $PACKAGE_DIR/DEBIAN/control && \
  echo \"Architecture: arm64\" >> $PACKAGE_DIR/DEBIAN/control && \
  echo \"Maintainer: ich777\" >> $PACKAGE_DIR/DEBIAN/control && \
  echo \"Description: libnvidia-container for MOS\" >> $PACKAGE_DIR/DEBIAN/control && \
  rm -rf $PACKAGE_DIR/usr/include $PACKAGE_DIR/usr/lib/aarch64-linux-gnu/*.a $PACKAGE_DIR/usr/lib/aarch64-linux-gnu/pkgconfig $PACKAGE_DIR/usr/lib/aarch64-linux-gnu/debug && \
  dpkg-deb --build package $BUILD_DIR/libnvidia-container_${LIBNVIDIA_VERSION}-1+mos_arm64.deb && \
  md5sum $BUILD_DIR/libnvidia-container_${LIBNVIDIA_VERSION}-1+mos_arm64.deb | cut -d ' ' -f1 > $BUILD_DIR/libnvidia-container_${LIBNVIDIA_VERSION}-1+mos_arm64.deb.md5"
